### ISSUE TITLE
Generate Swagger info for Restivus Default Authentication

### ISSUE THREAD

**Issue by JesperWe** [apinf/restivus-swagger#4]
Restivus comes with a useful [default authentication](https://github.com/kahmali/meteor-restivus/#default-authentication) setup. If it is activated for the Api, restivus-swagger could generate the corresponding info in the Swagger data:
- POST /login endpoint
- GET /logout endpoint
- Required headers for other endpoints (X-User-Id and X-Auth-Token)

...alternative question: If you consider this a bad idea, how could I manually add that to my swagger.json?

**Comment by jykae** [comment]
hello @JesperWe !

At first I have focused on getting things work without authentication, and that's the reason I have excluded those routes by default. Thanks for adding this to backlog! 
I want to have also way to choose whether to add defaultAuth routes info or not.

Currently, excluding routes is like this (which is bad.. I know),
https://github.com/apinf/restivus-swagger/blob/master/server/restivus-swagger.js#L46

The /login and /logout routes would need also swagger metadata added, otherwise just the routes get added, with empty swagger information => Invalid swagger.json

If you are able to look at this one, I would be happy to answer questions, I don't have too much time for improving at the moment. We at @apinf/developers are open :)

**Comment by dcantatore** [comment]
Can I work on this? I am using this for a project and would really like to be able to define the default login swagger. 

Is there any specific way you would want it implemented? Such as auto on with certain set text? Or a flag/property to turn it on and off?

**Comment by brylie** [comment]
@dcantatore we are open to discussion/suggestions regarding how this might be added. I like the property based approach for a couple of reasons:
- it is explicit whether the authentication routes are enabled or disabled
- the property might eventually be extensible, so there could be sub-fields or related fields
  - for now, a boolean field might suffice

What are your thoughts?

**Comment by dcantatore** [comment]
I agree with the property based approach, in the main swagger object. I'm thinking if it is not defined as true to have it default to the current behavior. 

The next thing I was thinking about what wether to have a default swagger path defined or where/how to let someone define the swagger path. 

Am I correct in saying that when you are putting the swagger information in the routes you can't also have paths in the main object? I think I tested this and found it to be the case. If so the swagger would mainly be prewritten and added to the doc var depending on the boolean property added. Or the restivus-swagger object could have another field it looks for custom swagger login route information.  Something as simple as login: and logout: within swagger.
...
Which leads to another idea - if they have the login, logout properties you could just check if they exist and add them. If not do nothing with the swagger routes. 
...
Do you know of a simple clean meteor project with routes and swagger definitions that I can clone? I'd rather not work on my current projects packages and would rather set up a simple test environment. 


Many ways to cook this egg.

**Comment by brylie** [comment]
> Am I correct in saying that when you are putting the swagger information in the routes you can't also have paths in the main object?

@jykae can you help clarify this question?

> Do you know of a simple clean meteor project with routes and swagger definitions that I can clone?

A quick search returned the following projects:

- [j-hack/meteor-bookmarks](https://github.com/j-hack/meteor-bookmarks)
  - [swagger definition](https://github.com/j-hack/meteor-bookmarks/blob/master/imports/api/rest.js#L13-L14)
- [jykae/ec-bazaar-api](https://github.com/jykae/ec-bazaar-api)
  - [swagger definition](https://github.com/jykae/ec-bazaar-api/blob/master/bazaar-api/server/api/config.js#L32)

> Many ways to cook this egg.

Jep, we have been reminding ourselves to find **simple**, **explicit** solutions, and build on them in an **iterative process**.

**Comment by dcantatore** [comment]
> Am I correct in saying that when you are putting the swagger information in the routes you can't also have paths in the main object?
@jykae can you help clarify this question?

I mean similar to this:
http://swagger.io/specification/#pathsObject
and this
http://stackoverflow.com/questions/35693770/open-api-post-with-path-parameter

That you can have the paths property in the primary swagger object. I have only written them within the route. Can they be defined in the main object when using restive-swagger?

*I'll be setting up tonight and trying out some ideas this weekend.

**Comment by dcantatore** [comment]
Hey @jykae @brylie,

I got setup and played around with some ideas yesterday. I think the best way to implement this will be to let people define routes in the swagger meta under a paths attribute. This way they can define the log in or log out how ever they want. 

In theory it would also make you able to have your swagger paths written before the routes even exists - almost in a test first development concept. It also would allow someone that doesn't know paths well but works on documentation to do so. And a final thing that it would enable is the ability to write routes with the default restivus setup of:

`get: function(){}`

instead of 
```
get:
action: function(){},
swagger:{
```

Of course this is mainly an opinion but it solves the other issue with default auth routes that just adding a boolean property still doesn't allow specifics in writing the actual route. You can't write the swagger for a login route with default auth enabled because addRoute sees duplicate routes.

I need to go over the code again but I think I can add this with about 10 lines of code and 2-3 loops -  if there are any paths in swagger.meta.paths, for checks against pre-existing swagger routes info that are already inserted into the doc object, and there might be one more check but I think that covers the additional code for the most part. 

If that sounds good I'll do a pull request tonight. Thanks!

**Comment by brylie** [comment]
> If that sounds good I'll do a pull request tonight. Thanks!

Really well thought-out! I like the flexibility your idea provides.

Let us know how we might be of support :smile_cat: 

/cc @bajiat

**Comment by dcantatore** [comment]
Pull request is in, I'll update the readme with instructions and such soon.

**Comment by dcantatore** [comment]
I added the readme updates in a pull request. Can you guys update the atmosphere package? Would love to get this working for my meteor projects api.

**Comment by brylie** [comment]
Jep. I am having trouble publishing to Atmosphere. I will try again on Monday.

**Comment by brylie** [comment]
@dcantatore I was able to publish to atmosphere this morning, version 0.3.0 with your changes.

For some reason, I had to pin npm-bcrypt to a lower version, since it was breaking the build process.

**Comment by jykae** [comment]
As original author, a friendly note for you that Restivus Swagger further development continues here: https://github.com/alfredjkwak/restivus-swagger

@dcantatore my implementation generates now /login & /logout with swagger meta

>In theory it would also make you able to have your swagger paths written before the routes even exists - almost in a test first development concept. It also would allow someone that doesn't know paths well but works on documentation to do so.

For design-first concept you mentioned I am trying to figure out best possible way to handle it, that would help someone who doesn't know paths so well. It would enable use of Swagger designer/editor to make swagger.json and generate stub of Restivus API.

So I warmly welcome you to check out my version, if it would be worth donating a lunch 🍴

**Comment by radik** [comment]
@brylie I could not use latest version of restivus-swagger because of npm-bcrypt version:
```bash
➜  app meteor add apinf:restivus-swagger@0.3.0
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint npm-bcrypt@=0.8.5 is not satisfied by npm-bcrypt 0.9.2.
Constraints on package "npm-bcrypt":
* npm-bcrypt@0.9.2 <- top level
* npm-bcrypt@=0.8.5 <- apinf:restivus-swagger 0.3.1
* npm-bcrypt@0.9.2 <- accounts-password 1.3.4 <- nimble:restivus 0.8.7 <- apinf:restivus-swagger 0.3.1
```
Here I'm trying to add apinf:restivus-swagger@0.3.0 to newly created meteor application.

Could you help me with this?

**Comment by brylie** [comment]
@radik please open a new issue for this report. I will investigate ASAP.

**Comment by brylie** [comment]
Closing this issue since it has been resolved by merging the PR #5.

**Comment by jykae** [comment]
@radik checkout https://github.com/meteor-rest/restivus-swagger Maybe it works for you?
Open an issue there if problems, Meteor REST community is willing help & maintain packages related to REST API design & development :) 

Version should not be strictly set in this package as the issue comes from upper level (as the error says), and development usually goes forward.

Recently built also another package, that might be interesting for you if like designing Swagger specs first, https://github.com/meteor-rest/generator-restivus 

I hope Meteor REST community could be one point stop in Meteor community to find out tools for REST API solutions.

**Comment by brylie** [comment]
cc: @bajiat
